import type { Config } from 'tailwindcss';

export default {
  content: ['./src/**/*.{astro,html,js,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#071325',
        'surface-dim': '#071325',
        'surface-bright': '#2e394d',
        'surface-container-lowest': '#030e20',
        'surface-container-low': '#101c2e',
        'surface-container': '#142032',
        'surface-container-high': '#1f2a3d',
        'surface-container-highest': '#2a3548',
        'on-surface': '#d7e3fc',
        'on-surface-variant': '#d0c5b2',
        'inverse-surface': '#d7e3fc',
        'inverse-on-surface': '#253144',
        outline: '#99907e',
        'outline-variant': '#4d4637',
        'surface-tint': '#e6c364',
        primary: '#e6c364',
        'on-primary': '#3d2e00',
        'primary-container': '#c9a84c',
        'on-primary-container': '#503d00',
        'inverse-primary': '#755b00',
        secondary: '#95d4b3',
        'on-secondary': '#003824',
        'secondary-container': '#12533a',
        'on-secondary-container': '#87c6a5',
        tertiary: '#cbc6bf',
        'on-tertiary': '#32302b',
        'tertiary-container': '#afaba4',
        'on-tertiary-container': '#41403a',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#ffe08f',
        'primary-fixed-dim': '#e6c364',
        'on-primary-fixed': '#241a00',
        'on-primary-fixed-variant': '#584400',
        'secondary-fixed': '#b1f0ce',
        'secondary-fixed-dim': '#95d4b3',
        'on-secondary-fixed': '#002114',
        'on-secondary-fixed-variant': '#0e5138',
        'tertiary-fixed': '#e7e2da',
        'tertiary-fixed-dim': '#cac6be',
        'on-tertiary-fixed': '#1d1c17',
        'on-tertiary-fixed-variant': '#494741',
        background: '#071325',
        'on-background': '#d7e3fc',
        'surface-variant': '#2a3548',
        foreground: '#d7e3fc',
        card: '#071325',
        'card-foreground': '#d7e3fc',
        popover: '#1f2a3d',
        'popover-foreground': '#d7e3fc',
        'primary-foreground': '#3d2e00',
        'secondary-foreground': '#003824',
        muted: '#142032',
        'muted-foreground': '#d0c5b2',
        accent: '#e6c364',
        'accent-foreground': '#503d00',
        destructive: '#ffb4ab',
        'destructive-foreground': '#690005',
        border: '#4d4637',
        input: '#99907e',
        ring: '#e6c364',
        sidebar: '#071325',
        'sidebar-foreground': '#d7e3fc',
        'sidebar-primary': '#e6c364',
        'sidebar-primary-foreground': '#3d2e00',
        'sidebar-accent': '#142032',
        'sidebar-accent-foreground': '#d0c5b2',
        'sidebar-border': '#4d4637',
        'sidebar-ring': '#e6c364',
      },
      fontFamily: {
        manrope: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['56px', { lineHeight: '64px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'display-lg-mobile': ['40px', { lineHeight: '48px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500', letterSpacing: '0.01em' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.05em' }],
      },
      borderRadius: {
        sm: '0.5rem',
        DEFAULT: '1rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        'container-padding-desktop': '40px',
        'container-padding-mobile': '20px',
        gutter: '24px',
        'stack-sm': '12px',
        'stack-md': '24px',
        'stack-lg': '48px',
        'section-gap': '120px',
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
} satisfies Config;
