import type { Config } from 'tailwindcss';

export default {
  content: ['./src/**/*.{astro,html,js,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#131313',
        foreground: '#e5e2e1',
        surface: '#1a1c1e',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#d0c5af',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#99907c',
        'outline-variant': '#4d4635',
        'surface-tint': '#e9c349',
        primary: '#d4af37',
        'on-primary': '#3c2f00',
        'primary-container': '#d4af37',
        'on-primary-container': '#554300',
        'inverse-primary': '#735c00',
        secondary: '#c6c6c9',
        'on-secondary': '#2f3133',
        'secondary-container': '#454749',
        'on-secondary-container': '#b4b5b7',
        tertiary: '#d1cec8',
        'on-tertiary': '#31312c',
        'tertiary-container': '#b5b3ad',
        'on-tertiary-container': '#464540',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#ffe088',
        'primary-fixed-dim': '#e9c349',
        'on-primary-fixed': '#241a00',
        'on-primary-fixed-variant': '#574500',
        'secondary-fixed': '#e2e2e5',
        'secondary-fixed-dim': '#c6c6c9',
        'on-secondary-fixed': '#1a1c1e',
        'on-secondary-fixed-variant': '#454749',
        'tertiary-fixed': '#e5e2db',
        'tertiary-fixed-dim': '#c9c6c0',
        'on-tertiary-fixed': '#1c1c18',
        'on-tertiary-fixed-variant': '#474742',
        card: '#201f1f',
        'card-foreground': '#e5e2e1',
        popover: '#2a2a2a',
        'popover-foreground': '#e5e2e1',
        'primary-foreground': '#3c2f00',
        'secondary-foreground': '#2f3133',
        muted: '#201f1f',
        'muted-foreground': '#d0c5af',
        accent: '#d4af37',
        'accent-foreground': '#554300',
        destructive: '#ffb4ab',
        'destructive-foreground': '#690005',
        border: '#4d4635',
        input: '#99907c',
        ring: '#d4af37',
        sidebar: '#131313',
        'sidebar-foreground': '#e5e2e1',
        'sidebar-primary': '#d4af37',
        'sidebar-primary-foreground': '#3c2f00',
        'sidebar-accent': '#201f1f',
        'sidebar-accent-foreground': '#d0c5af',
        'sidebar-border': '#4d4635',
        'sidebar-ring': '#d4af37',
      },
      fontFamily: {
        manrope: ['Manrope', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['56px', { lineHeight: '1.1', fontWeight: '700', letterSpacing: '-0.02em' }],
        'display-lg-mobile': ['40px', { lineHeight: '1.1', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-lg': ['40px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['28px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', fontWeight: '600', letterSpacing: '0.05em' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '600', letterSpacing: '0.05em' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        'container-padding-desktop': '64px',
        'container-padding-mobile': '16px',
        gutter: '24px',
        'stack-sm': '12px',
        'stack-md': '24px',
        'stack-lg': '48px',
        'section-gap': '120px',
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
} satisfies Config;
