import type { Config } from 'tailwindcss';

export default {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#071325',
        foreground: '#d7e3fc',
        surface: '#071325',
        'surface-dim': '#071325',
        'surface-bright': '#2e394d',
        'surface-container-lowest': '#030e20',
        'surface-container-low': '#101c2e',
        'surface-container': '#142032',
        'surface-container-high': '#1f2a3d',
        'surface-container-highest': '#2a3548',
        'on-surface': '#d7e3fc',
        'on-surface-variant': '#d0c5b2',
        'inverse-surface': '#d7e3fc',
        'inverse-on-surface': '#253144',
        outline: '#e6c364',
        'outline-variant': '#4d4637',
        'surface-tint': '#e6c364',
        primary: '#e6c364',
        'on-primary': '#241a00',
        'primary-container': '#e6c364',
        'on-primary-container': '#503d00',
        'inverse-primary': '#755b00',
        secondary: '#95d4b3',
        'on-secondary': '#ffffff',
        'secondary-container': '#95d4b3',
        'on-secondary-container': '#87c6a5',
        tertiary: '#cbc6bf',
        'on-tertiary': '#32302b',
        'tertiary-container': '#afaba4',
        'on-tertiary-container': '#41403a',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#ffe08f',
        'primary-fixed-dim': '#e6c364',
        'on-primary-fixed': '#241a00',
        'on-primary-fixed-variant': '#584400',
        'secondary-fixed': '#b1f0ce',
        'secondary-fixed-dim': '#95d4b3',
        'on-secondary-fixed': '#002114',
        'on-secondary-fixed-variant': '#0e5138',
        'tertiary-fixed': '#e7e2da',
        'tertiary-fixed-dim': '#cac6be',
        'on-tertiary-fixed': '#1d1c17',
        'on-tertiary-fixed-variant': '#494741',
        card: '#142032',
        'card-foreground': '#d7e3fc',
        popover: '#1f2a3d',
        'popover-foreground': '#d7e3fc',
        'primary-foreground': '#241a00',
        'secondary-foreground': '#ffffff',
        muted: '#142032',
        'muted-foreground': '#d7e3fc',
        accent: '#e6c364',
        'accent-foreground': '#503d00',
        destructive: '#ffb4ab',
        'destructive-foreground': '#690005',
        border: '#4d4637',
        input: '#e6c364',
        ring: '#e6c364',
        sidebar: '#071325',
        'sidebar-foreground': '#d7e3fc',
        'sidebar-primary': '#e6c364',
        'sidebar-primary-foreground': '#241a00',
        'sidebar-accent': '#142032',
        'sidebar-accent-foreground': '#d7e3fc',
        'sidebar-border': '#4d4637',
        'sidebar-ring': '#e6c364',
      },
      fontFamily: {
        manrope: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['clamp(40px, 5vw + 16px, 56px)', { lineHeight: '1.15', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-lg': ['clamp(28px, 2.5vw + 12px, 32px)', { lineHeight: '1.25', fontWeight: '600' }],
        'headline-md': ['clamp(20px, 1.5vw + 10px, 24px)', { lineHeight: '1.33', fontWeight: '600' }],
        'body-lg': ['clamp(16px, 0.5vw + 14px, 18px)', { lineHeight: '1.55', fontWeight: '400' }],
        'body-md': ['clamp(14px, 0.25vw + 13px, 16px)', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['clamp(12px, 0.2vw + 11px, 14px)', { lineHeight: '1.43', fontWeight: '500', letterSpacing: '0.01em' }],
        'label-sm': ['12px', { lineHeight: '1.33', fontWeight: '600', letterSpacing: '0.05em' }],
      },
      borderRadius: {
        sm: '0.5rem',
        DEFAULT: '1rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      boxShadow: {
        'luxury': '0 12px 32px rgba(0, 0, 0, 0.3)',
        'luxury-hover': '0 16px 40px rgba(0, 0, 0, 0.4)',
      },
      spacing: {
        base: '8px',
        'container-padding-desktop': '40px',
        'container-padding-mobile': '20px',
        gutter: '24px',
        'stack-sm': '12px',
        'stack-md': '24px',
        'stack-lg': '48px',
        'section-gap': '120px',
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
} satisfies Config;
